package de.bennyboer.author.server.shared.websocket.api;

public enum WebSocketMessageMethod {
    HEARTBEAT,
    EVENT,
    PERMISSION_EVENT,
    SUBSCRIBE,
    SUBSCRIBED,
    SUBSCRIBE_TO_PERMISSIONS,
    SUBSCRIBED_TO_PERMISSIONS,
    UNSUBSCRIBE,
    UNSUBSCRIBED,
    UNSUBSCRIBE_FROM_PERMISSIONS,
    UNSUBSCRIBED_FROM_PERMISSIONS,
}
