export enum UserEventType {
  USERNAME_CHANGED = 'USERNAME_CHANGED',
  PASSWORD_CHANGED = 'PASSWORD_CHANGED',
  MAIL_CHANGED = 'MAIL_CHANGED',
  IMAGE_CHANGED = 'IMAGE_CHANGED',
  RENAMED = 'RENAMED',
  REMOVED = 'REMOVED',
  OTHER = 'OTHER',
}
