export enum UserEventType {
  USERNAME_CHANGED = 'USERNAME_CHANGED',
  RENAMED_FIRST_NAME = 'RENAMED_FIRST_NAME',
  RENAMED_LAST_NAME = 'RENAMED_LAST_NAME',
  PASSWORD_CHANGED = 'PASSWORD_CHANGED',
  MAIL_UPDATED = 'MAIL_UPDATED',
  IMAGE_CHANGED = 'IMAGE_CHANGED',
  REMOVED = 'REMOVED',
  OTHER = 'OTHER',
}
